skip_if(!nzchar(system.file(package = "rgl")), "Rendering tests require rgl")

test_that("all families return widgets without losing rows or caller options", {
    old <- options(rgl.useNULL = TRUE)
    on.exit(options(old))
    X <- matrix(seq_len(30), ncol = 3)
    before <- rgl::rgl.dev.list()
    opt <- getOption("rgl.useNULL")
    w <- plot3D.plain(X, axes = TRUE, highlight = c(2L, 7L))
    expect_s3_class(w, "htmlwidget")
    info <- attr(w, "ivue")
    expect_equal(info$X, X)
    expect_equal(info$draw.ids$row, seq_len(10))
    expect_equal(which(info$highlight), c(2L, 7L))
    expect_identical(rgl::rgl.dev.list(), before)
    expect_identical(getOption("rgl.useNULL"), opt)
    same.camera <- plot3D.plain(X, camera = info$camera)
    expect_equal(attr(same.camera, "ivue")$camera, info$camera)
    expect_s3_class(plot3D.cont(X, seq_len(10), axes = TRUE), "htmlwidget")
    expect_s3_class(plot3D.cltrs(X, rep(c("a", "b"), 5)), "htmlwidget")
    expect_s3_class(plot3D.plain(matrix(c(1, 1, 1), 1), point.type = "sphere"), "htmlwidget")
})

test_that("existing device and subscene survive success and errors", {
    old <- options(rgl.useNULL = TRUE)
    on.exit(options(old))
    dev <- rgl::open3d(useNULL = TRUE)
    on.exit(rgl::close3d(dev), add = TRUE)
    rgl::points3d(1, 2, 3)
    sub <- rgl::newSubscene3d()
    snapshot <- rgl::scene3d(minimal = FALSE)
    X <- matrix(1:9, ncol = 3)
    w <- plot3D.plain(X)
    expect_equal(rgl::cur3d(), dev)
    expect_equal(rgl::currentSubscene3d(), sub)
    before <- rgl::rgl.dev.list()
    expect_error(plot3D.plain(X, layers = list(layer3D.callback(function(ctx) {
        rgl::open3d(useNULL = TRUE, silent = TRUE)
        stop("callback opened device")
    }))), "callback opened device")
    expect_identical(rgl::rgl.dev.list(), before)
    expect_equal(rgl::currentSubscene3d(), sub)
    expect_equal(rgl::scene3d(minimal = FALSE), snapshot)
    expect_error(plot3D.plain(X, layers = list(layer3D.callback(function(ctx) stop("layer failed")))), "layer failed")
    expect_equal(rgl::cur3d(), dev)
    expect_equal(rgl::currentSubscene3d(), sub)
    expect_equal(rgl::scene3d(minimal = FALSE), snapshot)
    expect_error(plot3D.plain(X, layers = list(layer3D.callback(function(ctx) rgl::set3d(dev)))), "must not")
    expect_equal(rgl::cur3d(), dev)
})

test_that("bad coordinates and controls fail explicitly", {
    X <- matrix(1:9, ncol = 3)
    expect_error(plot3D.plain(matrix(numeric(), 0, 3)), "at least")
    expect_error(plot3D.plain(data.frame(a = 1, b = "two", c = 3)), "numeric")
    expect_error(plot3D.plain(matrix(c(1, NA, 2), 1)), "finite")
    expect_error(plot3D.plain(X, highlight = c(1, 1.5)), "whole-number")
    expect_error(plot3D.plain(X, highlight = c(TRUE, NA, FALSE)), "nonmissing")
    expect_error(plot3D.plain(X, point.size = 0), "point.size")
    expect_error(plot3D.plain(X, sphere.radius = -1), "sphere.radius")
    expect_error(plot3D.cont(X, 1:3, size = 3), "scene controls")
    expect_error(plot3D.cont(X, 1:2), "per row")
    expect_error(plot3D.cltrs(X, c("a", "b")), "per row")
    expect_error(plot3D.plain(X, camera = list(unknown = 1)), "camera")
    expect_error(plot3D.plain(X, col = c("red", "blue")), "length")
    expect_error(plot3D.cont(X, 1:3, output.file = "no.html"), "scene controls")
})

test_that("layers serialize with validated indices and callback context", {
    X <- matrix(1:12, ncol = 3)
    captured <- NULL
    w <- plot3D.plain(X, layers = list(
        layer3D.edges(matrix(c(1, 2, 2, 3), 2, byrow = TRUE)),
        layer3D.path(c(1, 3, 4)), layer3D.labels(1L, "start"),
        layer3D.callback(function(ctx) captured <<- ctx)))
    expect_equal(captured$row.ids, seq_len(4))
    expect_equal(captured$X, X)
    types <- vapply(attr(w, "ivue")$scene$objects, function(x) x$type, character(1))
    expect_true("lines" %in% types || "linestrip" %in% types)
    expect_true("text" %in% types)
    expect_error(plot3D.plain(X, layers = list(layer3D.edges(matrix(c(1, 5), 1)))), "between")
    expect_error(layer3D.edges(matrix(c(1, 1), 1)), "Self-loops")
    expect_s3_class(plot3D.plain(X, layers = list(layer3D.path(integer()))), "htmlwidget")
    expect_error(plot3D.plain(X, layers = list(layer3D.path(6L))), "between")
})

test_that("there are no legacy exports and exports save after device cleanup", {
    exports <- getNamespaceExports("ivue")
    expect_false(any(grepl("\\.(html|widget)$", exports)))
    w <- plot3D.cont(matrix(1:9, ncol = 3), c(1, NA, 3))
    expect_identical(w$width, "100%")
    expect_false(grepl("ivue-legend", as.character(htmltools::tagList(w$prepend)), fixed = TRUE))
    expect_match(w$jsHooks$render[[2]]$data$legend, "ivue-legend")
    path <- tempfile(fileext = ".html")
    on.exit(unlink(c(path, sub(".html$", "_files", path)), recursive = TRUE))
    htmlwidgets::saveWidget(w, path, selfcontained = FALSE)
    expect_true(file.exists(path))
    expect_true(any(grepl("rglWebGL", readLines(path, warn = FALSE), fixed = TRUE)))
})

test_that("fresh installed or source sessions initialize without native graphics", {
    skip_if_not_installed("callr")
    root <- normalizePath(test_path("../.."))
    source <- file.exists(file.path(root, "DESCRIPTION")) && dir.exists(file.path(root, "R"))
    result <- callr::r(function(root, source) {
        options(rgl.useNULL = NULL)
        Sys.unsetenv("RGL_USE_NULL")
        if (source) pkgload::load_all(root, quiet = TRUE) else library(ivue)
        before <- "rgl" %in% loadedNamespaces()
        w <- ivue::plot3D.plain(matrix(1:9, ncol = 3))
        list(eager = before, widget = inherits(w, "htmlwidget"),
             devices = length(rgl::rgl.dev.list()), option = getOption("rgl.useNULL"))
    }, list(root, source))
    expect_false(result$eager)
    expect_true(result$widget)
    expect_equal(result$devices, 0)
    expect_null(result$option)
})
