test_that('prepared object summaries are bounded and leave raw data intact', {
    g <- prepare.graph(list(edges=data.frame(from=character(), to=character(), weight=numeric()),
                           vertices=as.character(seq_len(12000))), weight.type='unweighted')
    before <- serialize(g, NULL)
    output <- capture.output(result <- withVisible(print(g)))
    expect_match(output[1], '12000 vertices, 0 edges, 12000 isolates')
    expect_lte(length(output), 8L)
    expect_false(result$visible)
    expect_identical(result$value, g)
    expect_identical(serialize(g,NULL), before)
    sc <- color.scale.cont(1:3, color.map=function(x) stop('must not evaluate'))
    expect_output(print(sc), 'not evaluated')
    expect_identical(withVisible(print(sc))$value, sc)
    empty <- color.scale.groups(character())
    expect_output(print(empty), 'Levels: 0')
    groups <- color.scale.groups(paste0('group-', seq_len(1000)))
    expect_lte(length(capture.output(print(groups))), 6L)
    bins <- color.scale.cont(1:3, mode='binned', breaks=c(1,2,3))
    expect_output(print(bins), 'Bins: 2')
})
